name: Publisher

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Build Package
        run: |
          poetry install
          poetry build

      - name: Publish to PyPi
        run: poetry publish -u __token__ -p $PYPI_API_TOKEN
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
